name: marvel_nav_bar
description: package support bottom navigation with moving item selected
version: 0.0.0
author: mohammed alsultani<alsultani8886@gmail.com>
homepage: http://marvelsystems.com.sa
#  &https://github.com/MohammedAlSultani/marvel_nav_bottom

environment:
  sdk: ">=1.19.0 <3.0.0"
#  sdk: "<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.14
  provider: ^4.3.2+2
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
